name: rocket_twin
channels:
  - conda-forge
dependencies:
  - python
  - pytest
  - flake8
  - isort
  - black
  - pre-commit
  - cosapp
  - pyoccad
  - pythonocc-core
  - jupyterlite-core==0.3.0
  - jupyterlab~=4.1.6
  - notebook~=7.1.2
